import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/navbar/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Navbar />
        <div className="main_page">{children}</div>
      </body>
    </html>
  );
}
